"""Second

Revision ID: 169fdf3c6a35
Revises: 3aa70be1f19a
Create Date: 2023-04-02 21:30:48.286740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169fdf3c6a35'
down_revision = '3aa70be1f19a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zero_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('date_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_zero_table_id'), 'zero_table', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zero_table_id'), table_name='zero_table')
    op.drop_table('zero_table')
    # ### end Alembic commands ###
